name:  property_grid
version: 1.0.0
description:  >
  A dart implementation of a .NET like property grid control.  Has support for various 
  value "views" and "editors" for visualizing and editing the values for property items
  and is extensible with custom view and editor factories
author: Ali Akbar Vathi <ali.akbar@gmail.com>
homepage: https://github.com/coderespawn/dart-property-grid
dependencies:
  color_picker: ">=1.0.4 <2.0.0"
